/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    Candidates: typeof import('./components/Candidates.vue')['default']
    DetailedJobCard: typeof import('./components/DetailedJobCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    JobPosterForm: typeof import('./components/JobPosterForm.vue')['default']
    JobSearchBar: typeof import('./components/JobSearchBar.vue')['default']
    NavigationDrawer: typeof import('./components/NavigationDrawer.vue')['default']
    PosterDetailedJobCard: typeof import('./components/PosterDetailedJobCard.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortJobCard: typeof import('./components/ShortJobCard.vue')['default']
  }
}
